# - name: 下载prometheus helm包
#   shell: cd /tmp/;helm fetch stable/prometheus-operator;tar zxvf prometheus-operator*

# - name: 添加etcd监控
#   lineinfile:
#     path: /tmp/prometheus-operator/values.yaml
#     regexp: '^kibanaConfig'
#     line: "{{ PRO }}"

- name: test
  shell: helm install prometheus stable/prometheus-operator --set kubeEtcd.endpoints='{'{{ PRO }}'}' --set grafana.ingress.enabled=true --set grafana.ingress.hosts='{'grafa.bkeb.vip'}' --set prometheus.ingress.enabled=true --set prometheus.ingress.hosts='{'{{ PROME_URL }}'}'