---
- name: kubeadm reset
  shell: kubeadm reset -f
  ignore_errors: yes

- name: 分发ca证书
  copy: src={{ ca_dir }}/ca.pem dest=/etc/kubernetes/pki/ca.crt

- name: 分发ca.key证书
  copy: src={{ ca_dir }}/ca-key.pem dest=/etc/kubernetes/pki/ca.key


- name: copy kubernetes repo
  template:
    src: kubernetes.repo
    dest: /etc/yum.repos.d/kubernetes.repo

- name: install kube
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - kubeadm
    - kubelet
    - kubectl

- name: copy kubeadm config
  template:
    src: kubeadm.conf
    dest: /tmp/kubeadm.conf

- name: delete kubeconfig
  shell: rm $HOME/.kube -fr  

- name: kubeadm init
  shell: kubeadm init --config /tmp/kubeadm.conf > /tmp/kubeinstall.txt

- name: shell credit
  shell: tail -n 2 /tmp/kubeinstall.txt > /tmp/join.sh

- name: add master
  shell: cat /tmp/kubeinstall.txt |sed -n '/and then running the following as root/,/Then you can join any number/{/and service account/n;/Then you can join/b;p}' > /tmp/joinmaster.sh

- name: copy master file
  fetch:
    src: /tmp/joinmaster.sh
    dest: /tmp/joinmaster.sh
    flat: yes  

- name: copy file
  fetch:
    src: /tmp/join.sh
    dest: /tmp/joinkube.sh
    flat: yes

- name: copy key
  fetch: src={{ item }} dest={{ pki_dir }}/
  with_fileglob:
    - "/etc/kubernetes/pki/*"

- name: init kubectl
  shell: mkdir -p $HOME/.kube;sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config

# - name: cp calico file
#   template:
#     src: calico.yaml
#     dest: /root/calico.yaml



- name: calico install
  shell: kubectl apply -f https://docs.projectcalico.org/v3.14/manifests/calico.yaml

# - name: wget helm
#   get_url:
#     url: https://get.helm.sh/helm-v3.2.1-linux-amd64.tar.gz
#     dest: /tmp/helm-v3.2.1-linux-amd64.tar.gz

# - name: install helm
#   shell: cd /tmp/; tar zxvf ./helm-v3.2.1-linux-amd64.tar.gz;mv linux-amd64/helm /usr/local/bin/helm