- name: prepare some dirs
  file: name={{ item }} state=directory
  with_items:
  - "{{ bin_dir }}"
  - "{{ ca_dir }}"
  - "/var/lib/etcd"    # etcd 工作目录

- name: 下载etcd二进制文件
  copy: src={{ bin_dir }}/{{ item }} dest={{ bin_dir }}/{{ item }} mode=0755
  with_items:
  - etcd
  - etcdctl
  tags: upgrade_etcd

- name: 分发证书相关
  copy: src=/{{ ca_dir }}/{{ item }} dest={{ ca_dir }}/{{ item }}
  with_items:
  - ca.pem
  - ca-key.pem
  - ca-config.json


- name: 同步证书生成文件
  copy: src=/opt/{{ item }} dest={{ bin_dir }}/{{ item }} mode=0755
  with_items:
  - cfssl
  - cfssljson

- name: 同步etcd证书json文件
  template: src=etcd-csr.json.j2 dest={{ ca_dir }}/etcd-csr.json


- name: 生成etcd证书
  shell: "{{ bin_dir }}/cfssl gencert -ca={{ ca_dir }}/ca.pem -ca-key={{ ca_dir }}/ca-key.pem -config={{ ca_dir }}/ca-config.json -profile=kubernetes {{ ca_dir }}/etcd-csr.json | {{ bin_dir }}/cfssljson -bare {{ ca_dir }}/etcd"

- name: 创建etcd的systemd unit文件
  template: src=etcd.service dest=/etc/systemd/system/etcd.service
  tags: upgrade_etcd

- name: 开机启用etcd服务
  shell: systemctl enable etcd
  ignore_errors: true

- name: 开启etcd服务
  shell: systemctl daemon-reload && systemctl restart etcd
  ignore_errors: true
  tags: upgrade_etcd

- name: 以轮询的方式等待服务同步完成
  shell: "systemctl status etcd.service|grep Active"
  register: etcd_status
  until: '"running" in etcd_status.stdout'
  retries: 8
  delay: 8
  tags: upgrade_etcd

- name: 添加环境变量
  lineinfile: 
    dest: /etc/profile
    regexp: "{{ bin_dir }}"
    line: export PATH=${PATH}:{{ bin_dir }}  