- name: 同步二进制文件
  copy: src={{ bin_dir }}/{{ item }} dest={{ bin_dir }}/{{ item }} mode=0755
  with_items:
  - kubectl
  - kubelet
  - kube-proxy

- name: 重启kubelet等服务
  shell: systemctl daemon-reload && systemctl restart kube-proxy && systemctl restart kubelet