TMP_NODES: "{% for h in groups['etcd'] %}\"{{ h }}\",{% endfor %}"
ETCD_NODES: "{{ TMP_NODES.lstrip('\"').rstrip('\",').replace(',', ',\n    ') }}"
MASTER_CERT_HOSTS:
  - "192.168.3.51"
  - "k8s.rrjc.com"
CLUSTER_KUBERNETES_SVC_IP: "{{ SERVICE_CIDR | ipaddr('net') }}"  
