---
- name: docker init
  yum: 
    name: "{{ item }}"
    state: absent
  with_items:
    - docker
    - docker-ce
    - docker-common
    - docker-selinux
    - docker-engine

- name: copy file
  get_url: 
    url: http://mirrors.aliyun.com/docker-ce/linux/centos/docker-ce.repo 
    dest: /etc/yum.repos.d/docker-ce.repo
 
- name: yum docker
  package:
    name: "{{ item }}"
    state: present
  with_items: 
    - device-mapper-persistent-data
    - lvm2
    - docker-ce-18.09.9-3.el7.x86_64

- name: docker相关目录
  file: name=/etc/docker state=directory


- name: copy daemon
  template:
    src: daemon.json
    dest: /etc/docker/daemon.json

- name: copy sysctl
  template:
    src: k8s.conf
    dest: /etc/sysctl.d/k8s.conf

- name: reload systemctl
  shell: systemctl daemon-reload

- name: init sysctl
  shell: sysctl -p

- name: start docker service
  service: name=docker enabled=true state=started

# - name: copy config file
#   template:
#     src: docker.service
#     dest: /etc/systemd/system/docker.service

# - name: flush-iptables
#   shell: "iptables -P INPUT ACCEPT \
#             && iptables -F && iptables -X \
#             && iptables -F -t nat && iptables -X -t nat \
#             && iptables -F -t raw && iptables -X -t raw \
#             && iptables -F -t mangle && iptables -X -t mangle"
