---
- name: prepare some dirs
  file: name={{ item }} state=directory
  with_items:
  - "{{ bin_dir }}"
  - "{{ ca_dir }}"
  - /etc/docker
  
- name: 下载 docker 二进制文件(>= 18.09.x)
  copy: src={{ bin_dir }}/{{ item }} dest={{ bin_dir }}/{{ item }} mode=0755
  with_items:
  - containerd
  - containerd-shim
  - docker-init
  - runc
  - docker
  - ctr
  - dockerd
  - docker-proxy

- name: copy config file
  template:
    src: docker.service
    dest: /etc/systemd/system/docker.service

- name: copy daemon
  template:
    src: daemon.json
    dest: /etc/docker/daemon.json

- name: flush-iptables
  shell: "iptables -P INPUT ACCEPT \
            && iptables -F && iptables -X \
            && iptables -F -t nat && iptables -X -t nat \
            && iptables -F -t raw && iptables -X -t raw \
            && iptables -F -t mangle && iptables -X -t mangle"
          
- name: reload systemctl
  shell: systemctl daemon-reload            

- name: 开机启用docker 服务
  service: name=docker enabled=true state=started
  ignore_errors: true

- name: 添加环境变量
  lineinfile: 
    dest: /etc/profile
    regexp: "{{ bin_dir }}"
    line: export PATH=${PATH}:{{ bin_dir }}