---
- name: prepare some dirs
  file: name={{ item }} state=directory
  with_items:
  - "{{ ca_dir }}"

- name: 分发ca证书
  copy: src={{ ca_dir }}/ca.pem dest={{ ca_dir }}/ca.crt

- name: 分发ca.key证书
  copy: src={{ ca_dir }}/ca-key.pem dest={{ ca_dir }}/ca.key

- name: copy kubernetes repo
  template:
    src: kubernetes.repo
    dest: /etc/yum.repos.d/kubernetes.repo

- name: install kube
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - kubeadm
    - kubelet
    - kubectl

- name: kubeadm reset
  shell: kubeadm reset -f

- name: delete pki
  shell: rm /etc/kubernetes/pki/* -f

- name: copy join file
  copy:
    src: /tmp/joinkube.sh
    dest: /tmp/joinkube.sh

- name: join kube
  shell: sh /tmp/joinkube.sh