kind: Ingress
apiVersion: networking.k8s.io/v1beta1
metadata:
  name: myingress
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web

spec:
  rules:
  - host: {{ KIBANA_URL }}
    http:
      paths:
      - path: /
        backend:
          serviceName: kibana-kibana
          servicePort: 5601