apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: fast
provisioner: ceph.com/rbd
parameters:
  monitors: {{ CEPH_IP }}
  adminId: admin
  adminSecretName: ceph-secret
  adminSecretNamespace: kube-system
  pool: k8s
  userId: kube
  userSecretName: ceph-secret-user
  userSecretNamespace: default
  fsType: ext4
  imageFormat: "2"
  imageFeatures: "layering"